language: java
jdk:
  - oraclejdk8
services:
  - mongodb
  - redis
sudo: required
script: java -jar target/sbra-1.0-SNAPSHOT.jar
before_script: 
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn package